version: '3.8'

services:
  backend:
    build:
       context: ./backend
       dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 main:app --timeout 9999
    ports:
      - 5000:5000
  elasticsearch:
    image: elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - /home/ubuntu/islamGPT/app_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
  telegram:
    image: telegram_bot:latest
volumes:
  es_data: